name: Build all

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 3.10-0.9.8-0.13.8, 4.0-0.9.8-0.13.8, 4.0.1-0.9.8-0.13.8, 4.1.5-0.9.8-0.13.8, 4.1.7-0.9.8-0.13.8, 4.2.2-0.9.8-0.13.8, 4.2.5-0.9.8-0.13.8, 4.2.6-0.9.8-0.13.8, 4.2.9-0.9.8-0.13.8, ${VERSION}, latest ]
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/rtorrent-rutorrent-flood
          tags: |
            type=raw,value=${{ matrix.version }}

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v3
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/amd64
            linux/arm64/v8
          build-args: |
            RT_RU_VERSION=${{ matrix.version }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      -
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/rtorrent-rutorrent-flood
          readme-filepath: ./README.md